### ISSUE TITLE
Plugin doesn't work with the newest version of Dalamud.

### ISSUE THREAD

**Issue by Iaotle** [goaaats/Dalamud.LoadingImage#1]
Hi goaaats,

Amazing work on the new... well... everything!

Whenever you get around to it, please also update this mod :D

**Comment by HoB4588** [comment]
```
wait(2)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("Leaked IP: ##################" ,"All")
```

**Comment by HoB4588** [comment]
[]()![ไม่มีชื่อ 6_20211117052129.png](https://user-images.githubusercontent.com/95663872/144965744-bd5a6b8b-072e-406e-b038-3f3aa26807cc.png)
